
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibssnujohvguzgxgvkgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlic3NudWpvaHZndXpneGd2a2drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTU4NTYsImV4cCI6MjA2NTU3MTg1Nn0.iYXFKtcPofCpjUioewkEi90PzJYUpLjLN5mY3fdhecI";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
